---
- name: agg
  hosts: all
  vars:
    var1: "dog"
  
  tasks:
    - name: pass var1 to other jobs
      ansible.builtin.set_stats:
        data:
          test: "{{ var1 }}{{ var1 }}"
        aggregate: no
