---
- name: agg
  hosts: all
  
  tasks:
    - name: idk man
      ansible.builtin.set_stats:
        data:
          test: "{{ awx_job_id }}"
          something_else: "{{ var1 | default(omit) }}"
        aggregate: yes
