---
- hosts: all
  strategy: free
  serial: 1
  gather_facts: no
  vars:
    runit: true

  tasks:
    - import_role:
        name: sbf_debug
        tasks_from: debug.yml
      when: runit
      vars:
        debugmsg: baz
    - import_role:
        name: sbf_debug
        tasks_from: debug.yml
      when: runit
      vars:
        debugmsg: qux
    - import_role:
        name: sbf_debug
        tasks_from: debug_loop.yml
      when: runit

    # ---
    # #roles/foo/tasks/some.yml
    # - debug:
    #     var: bar
