---
- hosts: localhost
  gather_facts: no

  tasks:
    - import_role:
        name: sbf_debug
        tasks_from: debug.yml
      vars:
        debugmsg: baz
    - import_role:
        name: sbf_debug
        tasks_from: debug.yml
      vars:
        debugmsg: qux
    - import_role:
        name: sbf_debug
        tasks_from: debug_loop.yml

    # ---
    # #roles/foo/tasks/some.yml
    # - debug:
    #     var: bar
