- name: Vault lookup
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Return all secrets from a path
      community.general.hashi_vault:
        secret: kv/sbf:username 
        url: http://192.168.0.110:8200
