- name: Vault lookup
  hosts: 127.0.0.1
  connection: local
  collections:
    - community.general
  tasks:
    - name: Return all secrets from a path
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/sbf:username url=http://127.0.0.1:8200')}}"
