---
- name: loop1
  debug: msg="{{ item }}"
  loop: "{{ [1, 2, 3, 4, 5] }}"
  
- name: loop2
  debug: msg="{{ item }}"
  loop: "{{ [6, 7, 8, 9, 10] }}"
  
- name: loop3
  debug: msg="{{ item }}"
  loop: "{{ [1, 2, 3, 4, 5] }}"
 
